name: consultorio

description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.2.0
  get: ^4.5.1
  get_storage: ^2.0.3
  toggle_switch: ^1.3.0
  google_fonts: ^2.2.0
  flutter_slidable: ^1.1.0
  flutter_colorpicker: ^1.0.3
  url_launcher: ^6.0.15
  mask_text_input_formatter: ^2.0.0
  via_cep_flutter: ^0.2.2
  lottie: ^1.2.1
  supabase: ^0.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/imagens/
